import 'package:Pool_Rides/models/travel.dart';

List<Travel> travels = [
  Travel(
    driverName: "Edgar Medina Rifas",
    startTime: "3:00",
    arrivalTime: "5:00",
    priceTravel: 100.00,
    stars: 5,
    sourceName: "Guadalajara",
    destinyName: "Colima",
    imageDriver: "",
  ),
  Travel(
    driverName: "Mauricio Durán Padilla",
    startTime: "17:00",
    arrivalTime: "21:00",
    priceTravel: 200.00,
    stars: 5,
    sourceName: "Guadalajara",
    destinyName: "San Luis Potosí",
    imageDriver: "https://randomuser.me/portraits/men/2.jpg",
  ),
  Travel(
    driverName: "Anahí Santana",
    startTime: "12:00",
    arrivalTime: "15:30",
    priceTravel: 15.0,
    stars: 5,
    sourceName: "Guadalajara",
    destinyName: "Autlán",
    imageDriver: "https://randomuser.me/portraits/women/2.jpg",
  ),
  Travel(
    driverName: "Martín Casillas",
    startTime: "10:00",
    arrivalTime: "15:30",
    priceTravel: 15.0,
    stars: 5,
    sourceName: "Guadalajara",
    destinyName: "Puerto Vallarta",
    imageDriver: "https://randomuser.me/portraits/men/3.jpg",
  ),
  Travel(
    driverName: "Omar Soto",
    startTime: "14:00",
    arrivalTime: "15:30",
    priceTravel: 15.0,
    stars: 5,
    sourceName: "Guadalajara",
    destinyName: "Mazamitla",
    imageDriver: "https://randomuser.me/portraits/men/3.jpg",
  ),
  Travel(
    driverName: "Fernando Franco",
    startTime: "22:00",
    arrivalTime: "3:30",
    priceTravel: 15.0,
    stars: 5,
    sourceName: "Guadalajara",
    destinyName: "Toluca",
    imageDriver: "https://randomuser.me/portraits/men/4.jpg",
  ),
  Travel(
    driverName: "Gustavo Rueda",
    startTime: "13:30",
    arrivalTime: "3:30",
    priceTravel: 15.0,
    stars: 5,
    sourceName: "Guadalajara",
    destinyName: "Tapalpa",
    imageDriver: "https://randomuser.me/portraits/men/5.jpg",
  ),
];
